# Generated by Django 4.1.5 on 2023-01-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkp_new',
            name='kontakt_tel',
            field=models.PositiveIntegerField(verbose_name='Телефон контактного лица'),
        ),
        migrations.AlterField(
            model_name='tkp_new',
            name='summa_tkp',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в рублях с НДС', verbose_name='Сумма ТКП'),
        ),
    ]
