# Generated by Django 4.1.5 on 2023-01-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_tkp_new_kontakt_tel_alter_tkp_new_summa_tkp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tkp_new',
            name='kontakt_tel',
            field=models.BigIntegerField(verbose_name='Телефон контактного лица'),
        ),
        migrations.AlterField(
            model_name='tkp_new',
            name='summa_tkp',
            field=models.BigIntegerField(default=0, help_text='указывать сумму в рублях с НДС', verbose_name='Сумма ТКП'),
        ),
    ]
